(function(){var g=void 0,h=true,i=null,j=false,k,l=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function o(a,b){function c(){}c.prototype=b.prototype;a.U=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ba(){}
function ca(a,b,c){switch(typeof b){case "string":da(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==i){c.push("null");break}if(aa(b)=="array"){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),ca(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],typeof f!="function"&&(c.push(d),da(e,c),c.push(":"),ca(a,f,c),d=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ea={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},fa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function da(a,b){b.push('"',a.replace(fa,function(a){if(a in ea)return ea[a];var b=a.charCodeAt(0),e="\\u";b<16?e+="000":b<256?e+="00":b<4096&&(e+="0");return ea[a]=e+b.toString(16)}),'"')};var ga=/[?&]__cb_debug=([^&]+)/i,ha={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},ia={scroll:2E4,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},ja=/:\/\/static2\.chartbeat.com\/js\/chartbeat(_[a-z]+)?\.js$/;function ka(a,b){var c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}function la(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function ma(a,b){var c="",d=na(encodeURIComponent(a));d.splice(b||5,d.length);p(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function na(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,n=3285377520,m=[],q,w,z,L,M,Z=Math.ceil((a.length/4+2)/16),W=[Z],A=0,x;A<Z;A++){W[A]=[];for(q=0;q<16;q++)W[A][q]=a.charCodeAt(A*64+q*4)<<24|a.charCodeAt(A*64+q*4+1)<<16|a.charCodeAt(A*64+q*4+2)<<8|a.charCodeAt(A*64+q*4+3)}A=(a.length-1)*8;a=Z-1;W[a][14]=Math.floor(A/Math.pow(2,32));W[a][15]=A&4294967295;for(A=0;A<Z;A++){for(x=0;x<16;x++)m[x]=W[A][x];
for(x=16;x<80;x++)m[x]=(m[x-3]^m[x-8]^m[x-14]^m[x-16])<<1|(m[x-3]^m[x-8]^m[x-14]^m[x-16])>>>31;a=c;q=d;w=e;z=f;L=n;for(x=0;x<80;x++)M=Math.floor(x/20),M=(a<<5|a>>>27)+(M==0?q&w^~q&z:M==1?q^w^z:M==2?q&w^q&z^w&z:q^w^z)+L+b[M]+m[x]&4294967295,L=z,z=w,w=q<<30|q>>>2,q=a,a=M;c=c+a&4294967295;d=d+q&4294967295;e=e+w&4294967295;f=f+z&4294967295;n=n+L&4294967295}return[c,d,e,f,n]}
function oa(a){var b=l.navigator,c=l.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];p(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=l.performance;d=d.concat([b&&b.now?b.now():"",document.title,l.location.href,r(),la()]);return d.concat(a||[]).join()}function s(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}
function t(a){return typeof a!=="undefined"}function u(a){return a.replace(/^www\./,"")}function v(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function pa(a,b){var c=l;c.removeEventListener?c.removeEventListener(a,b,j):c.detachEvent&&c.detachEvent("on"+a,b)}function y(a){return typeof a==="number"}function B(a){return typeof a==="string"}function qa(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}
function r(){return(new Date).getTime()}function ra(a){return encodeURIComponent(a)}function sa(){return l.location.protocol==="https:"?"https:":"http:"}function C(a){return!!a&&a.constructor===Object}function ta(a,b){if(!C(a)||!C(b))return a===b;var c=0,d=h;p(a,function(a,e){c++;return d=a===b[e]});if(!d)return j;var e=0;p(b,function(){e++});return c===e}
function p(a,b){if(C(a)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===j)break}}function ua(a,b){var c=[];p(a,function(a,e){var f=b(a,e);c.push(f)});return c}function va(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}function wa(a){if(C(a)===j)return"";var b=[];p(a,function(a,d){b.push(encodeURIComponent(d)+"::"+encodeURIComponent(a))});return b.join("&")}
function xa(a){B(a)||(a="");var b={};p(a.split("&"),function(a){a=a.split("::");a.length===2&&(b[decodeURIComponent(a[0])]=decodeURIComponent(a[1]))});return b}
function ya(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,n=a.length;f<=n;f++)c[0][f]=f;for(var m,q,w,d=1;d<=e;d++)for(f=1;f<=n;f++)m=d-1,q=f-1,w=c[m][q],b.charAt(m)==a.charAt(q)?c[d][f]=w:(q=c[d][q]+1,m=c[m][f]+1,w+=2,c[d][f]=Math.min(q,m,w));return c[b.length][a.length]}var za;function Aa(){}var Ba=l.setInterval,Ca=l.clearInterval,Da=l.setTimeout,D=l.clearTimeout;
function Ea(a,b){var c={};p(b,function(b,e){c[b]=s(a[e],a)});return c}function Fa(a){var b=[];if(!C(a))return b;for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}function Ga(a){switch(a){case g:return"undefined";case "":return"empty";default:return a}};function Ha(a,b,c){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");for(var d=[],b=c.getElementsByTagName(b),c=b.length;c--;)b[c].getAttribute(a)&&d.push(b[c]);return d}function E(a,b){var c=i;b&&(c=b.getAttribute(a));if(c===i){var d=Ha(a,"*",b);d.length!==0&&(c=d[0].getAttribute(a))}return c}
function Ia(a,b,c){c=c||"";if(a===g)a=j;else{var d;if(!(d=c===""&&a.getAttribute(b)))if(d=a.getAttribute(b))d=a.getAttribute(b)===c;a=d?a:a===document.body?j:Ia(a.parentNode,b,c)}return a}function Ja(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=Ha("data-cb-scroll-element"))&&c.length)return c[0][b];if(y(l[a]))return l[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}
function Ka(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}function La(){return Ka("Height")}function Ma(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}
function Na(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return i;var d=a.ownerDocument.documentElement,e=0,f=t(c)?c+1:-1;B(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return i}function Oa(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function Pa(a){a=a||window.event;return!a?i:Na(a.target||a.srcElement,Oa,10)}function Qa(a,b){var c=document.createElement(a);p(b,function(a,b){c.setAttribute(b,a)});return c}function Ra(a){var b=t(g)?g:{};b.src=a;a=Qa("script",b);a.setAttribute("type","text/javascript");b=document.head||document.getElementsByTagName("head")[0];t(g)?g.appendChild(a):b&&b.appendChild(a)}
function Sa(){if(t(Ta))return Ta;var a;a:{a=document.getElementsByTagName("script");for(var b=a.length-1;b>-1;b--)if(ja.test(a[b].getAttribute("src"))){a=a[b];break a}a=g}return Ta=t(a)}var Ta;function Ua(){this.Y={};this.Hb=1}k=Ua.prototype;k.M=function(a,b,c){this.Hb++;this.Y[a]=this.Y[a]||{};this.Y[a][this.Hb]=[b,c];return this.Hb};k.T=function(a){if(B(a))this.Y[a]=g,delete this.Y[a];else if(y(a)){var b=h;p(this.Y,function(c){p(c,function(d,e){if(parseInt(e,10)===a)return c[e]=g,delete c[e],b=j});return b})}};k.S=function(a,b){if(this.Y[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];p(this.Y[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
k.addEventListener=function(a,b){var c=this.M(a,b);b._cbEventId=c};k.removeEventListener=function(a,b){this.Y[a]&&this.Y[a][b._cbEventId]&&this.Y[a][b._cbEventId][0]===b&&this.T(b._cbEventId)};var F=new Ua,Va="o",Wa={M:Va,T:"f"},Xa="a";var G={};
G.q=function(){G.ub?G.Ua("pageload"):(G.pc=[{target:l,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:l,event:"resize"},{target:document.body,event:"mousedown"}],G.eb=i,G.la=i,G.tb={},G.sb={},G.cc={},G.fb={},p(G.pc,function(a){var b=a.event;v(a.target,b,function(a){G.Ua.call(G,b,a)})}),F.M("f",function(){G.Ua("focus")}),G.Ua("pageload"),v(document.body,"click",function(a){(a=Pa(a))&&F.S("c",a)},h),v(document.body,"contextmenu",function(a){(a=Pa(a))&&
F.S("r",a)}),G.ub=h)};G.uc=function(){var a,b=G.cc.keydown;if(b===g)return j;b=r()-b;return b<=(a||15E3)&&b>=0};G.Da=function(a,b){var c=G.fb[a];if(!c)return"";var b=b||r(),d,e=0;p(c,function(a){d=Math.floor((b-a)/1E3);d>=0&&d<16&&(e|=1<<d)});c=("0000"+e.toString(16)).slice(-4);return c=="0000"?"":c};G.Zc=function(){G.fb={}};G.Nb=100;
G.Ua=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}G.dd(a);if(G.eb===i)G.kc(a);else if(!G.la||ha[G.la]<ha[a]||ia[G.la]<ia[a])G.la=a};G.dd=function(a){var b=r();G.cc[a]=b;var c=G.fb[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();G.fb[a]=c};G.kc=function(a){G.eb=Da(G.yc,G.Nb);F.S(Xa);G.tb[a]!==i&&D(G.tb[a]);G.sb[a]!==i&&D(G.sb[a]);G.ic(a,G.tb,ha,"i");G.ic(a,G.sb,ia,"j")};
G.ic=function(a,b,c,d){b[a]=Da(function(){D(b[a]);delete b[a];var c=j;p(b,function(){c=h;return j});c||F.S(d)},c[a]+G.Nb)};G.yc=function(){D(G.eb);G.eb=i;if(G.la)G.kc(G.la),G.la=i};var Ya,Za,$a,ab,bb;(function(){var a,b;p(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof l.document[a]==="boolean")return b=c,j});b!==g&&(ab=a,bb=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),$a=b+"visibilitychange")})();var cb=j;function db(){cb=bb&&l.document[bb]==="prerender"?h:j}function eb(){Za=h;F.S("f")}function fb(){Za=j;F.S("b")}
function gb(a,b,c){l.addEventListener?l.addEventListener(a,c,j):l.document.attachEvent&&l.document.attachEvent(b,c)}function hb(){var a=h;l.document.hasFocus&&(a=l.document.hasFocus());var b=j;ab&&(b=l.document[ab]);return a&&!b}function ib(){hb()?eb():fb()}function jb(a){db();if(cb){var b=j,c=function(){b||(db(),cb||(b=h,a(),l.window.setTimeout(function(){l.document.removeEventListener($a,c,j)},100)))};l.document.addEventListener($a,c,j)}else a()};function H(){this.k=l._sf_async_config||{};this.Tb=s(this.gc,this)}H.prototype.q=function(){this.Cb=0};H.prototype.gc=function(){};H.prototype.Ka=function(a){cb||ka(a,this.Tb)};H.prototype.ba=function(){this.Tb=i};function kb(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),p(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function lb(a,b){var c="",d=l.location.href.split("?");if(d.length){var d=kb(d[1]),e=b||a;d[e]&&(c=d[e])}return c}function mb(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function nb(a,b){var c=[];p(b,function(b){var e=a[b];t(e)&&(Object.prototype.toString.call(e)==="[object Array]"?p(e,function(a){c.push(b+"="+a)}):C(e)?p(e,function(a,b){c.push(b+"="+a)}):((e+"").length||b=="r")&&c.push(b+"="+e))});c.push("_");return c.join("&")}
function ob(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=l.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=mb(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?"/"+a:e.substr(0,f)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(mb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function pb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash}function qb(){var a=0,b=(l.location.search||"").match(ga);b&&b[1]&&(a=parseInt(b[1],10));return a};var rb="adIdentifier";function I(a,b,c){a[b]=a[b]||c}function sb(a,b){for(var c=l[a]||[];c.length;)b(c.shift());l[a]={push:b}}function tb(a){p(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=kb(b.src.split("?")[1]),I(a,"uid",b.uid),I(a,"domain",b.domain),j})}function ub(a,b){return a[b]?encodeURIComponent(a[b]):""}function vb(a){var b={};p(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};function wb(a){var b=a===document.documentElement?a.scrollHeight:a.offsetHeight,c=a.offsetWidth;if(b<=1||c<=1){var d=xb(a,["overflow","overflow-x","overflow-y"]);d.overflow==="hidden"||d["overflow-x"]==="hidden"||d["overflow-y"]==="hidden"||p(a.getElementsByTagName("iframe"),function(a){var d=a.offsetHeight,a=a.offsetWidth;if(d>1&&a>1)return b=d,c=a,j})}return{height:b,width:c}}function yb(a){a=wb(a);return a.height*a.width}
function zb(a){var b;"contains"in document.documentElement&&!document.documentElement.contains(a)?b=j:(b=wb(a),b=b.height>1&&b.width>1);if(!b)return j;b=xb(a,["visibility","display","overflow","opacity"]);if(b.visibility=="hidden"||b.display=="none"||b.opacity=="0")return j;if(b.overflow=="hidden"&&(a.offsetHeight==0||a.offsetWidth==0))return j;b=h;for(var c=a.parentElement;c&&b;){var d;if(c.scrollHeight===c.clientHeight&&c.scrollWidth===c.clientWidth)d=j;else{var e=xb(c,["overflow","overflow-x",
"overflow-y"]);d=e.overflow;var f=e["overflow-x"],e=e["overflow-y"];d=d==="auto"||d==="scroll"||f==="auto"||f==="scroll"||e==="auto"||e==="scroll"}d&&(b=Ab(a,c));c=c.parentElement}return b&&Ab(a,i)}function Ab(a,b){var c,d;if(b){var e=wb(b);c=e.width;d=e.height}else c=Ka("Width"),d=La();var f=wb(a),e=f.height,f=f.width,n=Bb(a,b),m=n.y,n=n.x;c=Math.min(n+f,f,c,c-n);d=Math.min(m+e,e,d,d-m);if(c<0||d<0)return j;e*=f;return c*d>=(e>=242500?0.3:0.5)*e}
function Bb(a,b,c){var d=a.offsetLeft,e=a.offsetTop,f=Cb(a);d+=f.x;e+=f.y;for(var n=j,m=c?0:Math.floor(Ja("X","Left",g)),q=c?0:Math.floor(Ja("Y","Top",g)),f=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===f)f=Cb(a),d+=a.offsetLeft+f.x,e+=a.offsetTop+f.y,f=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(xb(a,["position"]).position==="fixed"){n=h;break}a=a.parentElement}c||(d-=b?b.scrollLeft:m,e-=b?b.scrollTop:q);n&&(d+=m,e+=q);return{x:d,y:e}}
function xb(a,b){var c={},d,e;l.getComputedStyle?d=l.getComputedStyle(a,i):a.currentStyle?e="currentStyle":a.style&&(e="style");p(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[e][b]});return c}var Db=/matrix(3d)?\((.*)\)/;function Cb(a){var b={x:0,y:0},a=xb(a,["transform"]).transform;if(!B(a))return b;var c=a.match(Db);if(!c)return b;var a=c[2].split(", "),d;t(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};var J={},Eb={nb:"g"};J.Ob={IDLE:0,rc:1,qc:2,La:3};J.sc={IDLE:0,rc:1,qc:2,La:3};J.Z=0;J.$=0;J.q=function(){if(!J.ub)F.M(Xa,J.Jc,J),F.M("i",J.Oc,J),F.M("f",J.Lc,J),F.M("b",J.Kc,J),F.M("j",J.Nc,J),J.ub=h};J.nb=function(){return J.Z};J.Hc=function(){return J.$};J.Jc=function(){J.Z===1?J.ja(3):J.Z===0&&J.ja(2);J.$===1?J.ia(3):J.$===0&&J.ia(2)};J.Oc=function(){J.Z===3?J.ja(1):J.Z===2&&J.ja(0)};J.Nc=function(){J.$===3?J.ia(1):J.$===2&&J.ia(0)};
J.Lc=function(){(J.Z===0||J.Z===2)&&J.ja(3);(J.$===0||J.$===2)&&J.ia(3)};J.Kc=function(){J.Z===3?J.ja(2):J.Z===1&&J.ja(0);J.$===3?J.ia(2):J.$===1&&J.ia(0)};J.ja=function(a){J.Z=a;F.S("s",a)};J.ia=function(a){J.$=a;F.S("x",a)};function Fb(a,b){this.qb=a||g;this.Ja=b||g;this.ga=this.N=0;this.Xb=s(this.Sc,this);this.Fb=this.aa=i}k=Fb.prototype;k.q=function(){this.ga=this.N=0;this.aa=i;this.Fb=F.M("s",this.Ea,this);this.Ea(J.nb())};k.Ea=function(a){Ca(this.aa);this.aa=i;if(a===J.Ob.La)this.aa=Ba(this.Xb,1E3)};k.Sc=function(){if(this.qb===g||this.qb())this.N++,this.ga++,this.Ja&&this.Ja()};k.terminate=function(){Ca(this.aa);this.aa=i;F.T(this.Fb)};k.ba=function(){this.terminate();this.Ja=this.qb=g};function Gb(){H.call(this);this.Ib=s(this.Ib,this);this.Qb=0;this.kb=Hb;this.q()}o(Gb,H);Gb.prototype.q=function(){Gb.U.q.call(this);this.Qb++;this.G={};this.G.siteId="";this.mb=j;this.Pb=Ib;this.Sb=this.oc=j;this.Kb={};this.mc=j;this.gb=0;this.za=i;this.hd=F.M("s",this.Wb,this);this.Wb(J.nb())};var Hb=0,Ib=0;k=Gb.prototype;k.Wb=function(a){if(this.za!==i)Ca(this.za),this.za=i;this.gb=0;if(a===J.Ob.La)this.za=Ba(this.Ib,100)};
k.Ib=function(){if(zb(this.Na.Q)){if(this.gb++,this.gb>=10)this.mc=h,Jb(this),F.S("p")}else this.gb=0;this.Ac&&this.Ac.update()};function Jb(a){F.T(a.hd);Ca(a.za);a.za=i}k.$a=function(a){if(a.exclude)this.mb=h;this.Sb=!!a.dynamicLogic;this.G=a;F.S("p");if(a=a.vizu)this.oc=h,this.Kb=xa(a),F.S("z",this.Kb,this.Na.da.N)};
function Kb(a){var b=encodeURIComponent(a.an),c=a.aE,d=a.ax,e=a.ay,f=a.aw,n=a.ah,m=encodeURIComponent(a.av||""),q=encodeURIComponent(a.ac||""),w=encodeURIComponent(a.aP||""),z=encodeURIComponent(a.aS||""),L=encodeURIComponent(a.aH||""),M=encodeURIComponent(a.aW||""),Z=encodeURIComponent(a.aL||""),W=a.ao,A=a.aR,x=a.am,Gc=a.aV?"1":"0";a.exclude&&(q="");return b+"="+[c,d,e,f,n,q,m,W+"."+A,Gc,w,z,L,M,Z,x].join("::")}
k.ma=function(a,b){a.siteId=E("data-cb-site-id",b)||"";a.dynamicLogic=E("data-cb-dynamic-logic-id",b)||"";if(E("data-cb-exclude",b))this.mb=h;return a};k.refresh=function(){Jb(this);this.q()};k.ba=function(){Gb.U.ba.call(this);Jb(this)};function K(a){this.P=a;this.qa=a.getAttribute("data-cb-ad-id")||a.id||"";this.ob=1;var b=this;this.da=new Fb(function(){Lb(b);return zb(b.Q)},s(this.Ja,this));Mb&&this.Ma();this.q()}var Mb;K.prototype.Ja=function(){F.S("e",this);if(this.H){var a=this.H;a.oc&&F.S("z",a.Kb,1)}this.Pa&&this.Pa.update()};
K.prototype.q=function(){this.G={};this.G.campaignId="";this.G.creativeId="";this.G.placementId="";this.G.server_height="";this.G.server_width="";this.G.lineId="";this.Q=this.P;this.Ta=this.vb=this.rb=this.xb=j;this.fa={};this.fa.iab=j;this.fa.frame=j;this.fa.roadblock=j;Lb(this);this.da.q()};K.prototype.Ma=function(){var a=this;this.Pa=new Mb(this.qa,function(){return{adContainer:a.P,creativeContainer:a.Q,creativeScenarios:a.fa,adData:Nb(a)}})};
var Ob={300:{250:1,600:1,1050:1},180:{150:1},160:{600:1},728:{90:1},970:{90:1,66:1,250:1,415:1,550:1},120:{60:1},88:{31:1},62:{88:1},196:{31:1}};
function Lb(a){var b=l._sf_async_config;if(b&&(b=b.creativeDetection,b===j||B(b)&&b!=="iab"))return;var c=yb(a.P);if(a.Q!==a.P)if(b=yb(a.Q),b>c||b===0)a.Q=a.P;else if(b>0)return;p(["iframe","embed","object","img","div"],function(b){p(a.P.getElementsByTagName(b),function(b){var d=wb(b);if(!(d.height*d.width>c)&&Ob[d.width]&&Ob[d.width][d.height])return a.Q=b,a.fa.iab=h,j});return a.Q===a.P})}
K.prototype.$a=function(a,b){if(a.noRefresh)this.xb=h;var c=a.roadblock;this.vb=(this.Ta=c==="master")||c==="companion";this.fa.roadblock=c||j;this.G=a;if(this.rb=!!b){if(c=l._sf_async_config)if(c=c.creativeDetection,c===j||B(c)&&c!=="iframe")return;if(yb(b)>0)this.Q=b,this.fa.frame=h}this.H&&this.H.$a(a)};function N(a,b){return a.G&&t(a.G[b])?a.G[b]:""}var O="engagedSeconds",Pb={od:"id",nd:O,kd:"campaignId",ld:"creativeId",pd:"placementId",md:"element"};
function Qb(a){var b={};b.id=a.qa;b[O]=a.da.N;b.campaignId=N(a,"campaignId");b.creativeId=N(a,"creativeId");b.placementId=N(a,"placementId");return b}
function Nb(a){var b={};b.an=a.qa;b.aE=a.da.N;if(a.Q){var c=Bb(a.Q,g,h);b.ax=c.x;b.ay=c.y;c=wb(a.Q);b.aw=c.width;b.ah=c.height}b.ac=N(a,"campaignId");b.av=N(a,"creativeId");b.aP=N(a,"placementId");b.aW=N(a,"server_width");b.aH=N(a,"server_height");b.aL=N(a,"lineId");if(a.H)a=a.H,b.aV=a.mc,b.ao=a.Qb,b.aS=N(a.Na,"siteId"),b.exclude=a.mb,b.am=a.kb,b.aR=a.Pb;return b}
K.prototype.ma=function(){if(!this.rb){var a=this.P,b={};b.campaignId=E("data-cb-campaign-id",a)||"";b.creativeId=E("data-cb-creative-id",a)||"";b.placementId=E("data-cb-placement-id",a)||"";b.server_height=E("data-cb-creative-height",a)||"";b.server_width=E("data-cb-creative-width",a)||"";b.lineId=E("data-cb-line-id",a)||"";b.roadblock=E("data-cb-roadblock",a)||"";this.H&&this.H.ma(b,a);if(E("data-cb-no-refresh",a))this.xb=h;ta(b,this.G)||this.$a(b)}};
K.prototype.refresh=function(){this.da.terminate();this.H&&this.H.refresh();this.q()};K.prototype.terminate=function(){this.da&&this.da.ba();this.G=this.Q=this.P=i;this.Pa&&this.Pa.dispose();this.H&&this.H.ba()};var P={};P.xc=function(){try{P.create("_cb_test","1",1);var a=P.D("_cb_test");P.remove("_cb_test");return a==="1"}catch(b){return j}};P.D=function(a){a+="=";var b="";p(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
P.create=function(a,b,c){var d=l._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(r()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};P.remove=function(a){return P.D(a)?P.create(a,"",-86400):""};var Q={};Q.J=function(a){var b=l._sf_async_config;if(!a&&b&&b.noCookies)return i;if(Q.J.lb!==g)return Q.J.lb;var a=r()+"",c,d;try{if((d=l.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return Q.J.lb=d}catch(e){}return Q.J.lb=i};Q.D=function(a){var b=Q.J();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&r()>c)?(Q.remove(a),""):b.getItem(a)||""};
Q.create=function(a,b,c){var d=Q.J();if(d){var e=new Date;e.setTime(r()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};Q.remove=function(a){var b=Q.J();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Rb(a){this.Wa=a||"";this.zc=Q.J()!==i||P.xc();this.Gb=j;Sb(this)}k=Rb.prototype;k.isSupported=function(){return this.zc};
function Sb(a){if(!P.D("_cb_ls")){var b=Q.J()!==i,c=P.D("_SUPERFLY_lockout");c&&p(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,h)});var d=P.D("_chartbeat3");d&&(a.create("_v__chartbeat3",d,34128E3,h),P.remove("_chartbeat3"));b&&((b=P.D("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,h),(b=P.D("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,34128E3,h),(b=P.D("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));P.create("_cb_ls","1",34128E3)}}
function Tb(a){var b=a.Gb;a.Gb=j;return b}k.create=function(a,b,c,d){a=d?a:this.Wa+a;(Q.J()?Q:P).create(a,b,c);Q.J()&&P.create(a,b,c)};k.update=function(a,b,c,d,e,f,n){a=d?a:this.Wa+a;e=B(e)?e:"::";d=(d=this.D(a,h))?d.split(e):[];if(n&&d.length){var m=n(b),q=va(d,function(a){return n(a)===m});q!==-1&&d.splice(q,1)}d.push(b);for(y(f)&&d.length>f&&d.splice(0,d.length-f);d.length>1&&d.join(e).length>4E3;)d.shift();this.create(a,d.join(e),c,h)};
k.D=function(a,b){var a=b?a:this.Wa+a,c=(Q.J()?Q:P).D(a);if(!c&&Q.J()&&(c=P.D(a))&&P.D("_cb_ls")){this.Gb=h;var d;switch(a){case "_SUPERFLY_lockout":d=600;break;case "_chartbeat4":d=60;break;case "_cb_cp":d=60;break;case "_chartbeat3":d=34128E3;break;default:d=34128E3}Q.create(a,c,d)}return c};k.remove=function(a,b){a=b?a:this.Wa+a;(Q.J()?Q:P).remove(a);Q.J()&&P.remove(a)};function Ub(a){var b=i;if(a&&(b=Vb()))return b;var c=l.location,b=R(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function Vb(){var a=i;p(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=ob(b.href),a=R(b.pathname)+b.search+b.hash,j});return a}
for(var Wb={},Xb=0;Xb<81;Xb++)Wb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Xb)]=h;function Yb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Wb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function R(a){if(!B(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Yb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function S(a,b){var c=T();return t(b)&&!t(c[a])?b:c[a]}function T(){t(l._cb_shared)||(l._cb_shared={});return l._cb_shared};function Zb(a,b){Fb.call(this,a,b)}o(Zb,Fb);Zb.prototype.q=function(){this.ga=this.N=0;this.aa=i;this.Fb=F.M("x",this.Ea,this);this.Ea(J.Hc())};Zb.prototype.Ea=function(a){Ca(this.aa);this.aa=i;if(a===J.sc.La)this.aa=Ba(this.Xb,1E3)};function U(){H.call(this);this.sa=[];this.F=new Rb(this.lc);this.F.remove("_SUPERFLY_nosample");this.O=new Fb;this.pa=new Zb;this.Ab=s(this.wa,this);v(l,"unload",this.Ab);jb(s(this.q,this))}o(U,H);k=U.prototype;k.Za=h;
k.q=function(){U.U.q.call(this);this.Ra=this.ha=0;this.ka=r();this.ya=ma($b(this));this.xa=h;this.wb=72E5;if(this.Za){var a=+this.k.sessionLength;if(!isNaN(a))this.wb=a*6E4}a=S("d");if(!a){var a=[],b=this.F.D("_chartbeat2",h);b.length>0&&(a=b.split("."));a.length>4&&(a=[]);var b=r(),c=this.F.D("_cb",h);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var d=b-+(a[1]||0),e=b-+(a[2]||0);T().n=c&&d>18E5&&e<2592E6?0:1;var e="1",f=a&&+a[2],d=a&&a[3];if(a&&f&&d)if(e=Math.abs((qa(b)-qa(f))/864E5)){e=Math.min(e,16)-
1;for(f="";e--;)f+=0;e=(d+f+"1").slice(-16)}else e=d;d=e;c||(c=this.k.utoken||ma($b(this),3),a[1]=b);a[2]=b;a[3]=d;this.k.utoken=this.na;this.F.create("_cb",c,34128E3,h);this.F.create("_chartbeat2",a.join("."),34128E3,h);a[0]=c;T().d=a}this.sd=a.join(".");var n;c=+a[1];d=+a[2];if((b=a[3])&&c&&d)n=(Math.min((Math.abs((qa(d)-qa(c))/864E5)||0)+1,16,b.length)-1).toString(16),n+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.Vb=n;this.Uc=S("n",1);this.na=a[0];this.O.q();this.pa.q();J.q();G.q();Ya||
(Za=hb(),$a&&l.document.addEventListener&&l.document.addEventListener($a,ib,j),gb("focus","onfocusin",eb),gb("blur","onfocusout",fb),Za&&eb(),Ya=h);this.Ha=0;this.ib=F.M(Xa,this.zb,this)};k.oa=function(){if(!this.F.D("_SUPERFLY_lockout")&&!cb)this.Tc?this.ab():(this.Tc=h,!l._sf_async_config&&!l._cbq?(this.Va=s(this.ab,this),v(l,"load",this.Va)):this.ab())};k.ab=function(){var a=l._sf_startpt,b=l._sf_endpt;if(y(a))this.Bb=y(b)?b-a:r()-a;G.q();a=s(this.Ia,this);this.Yb=Ba(a,15E3);this.Ia()};
k.Ia=function(){var a=this.O.ga,a=this.k.reading&&+this.k.reading||a>0;if(this.Ra<this.ha&&!a)this.Ra++;else{var b;if(za===g)b=l.navigator.userAgent,za=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=za;b&&!a?this.Ra++:(a?this.ha=0:ac(this),this.Ra=0,this.sa.push(0),this.sa.length>18&&this.sa.shift(),this.Za&&r()-this.ka>=this.wb?this.terminate():this.ca())}};
function bc(a){var b={};b.g=a.k.uid;b.g0=ub(a.k,"sections");b.g1=ub(a.k,"authors");b.g2=ub(a.k,"zone");b.g3=ub(a.k,"sponsorName");b.g4=ub(a.k,"type");!a.k.noCookies&&a.F.isSupported()?b.n=a.Uc:b.nc=1;b.c=Math.round((r()-a.ka)/600)/100;b.E=a.O.N;b.EE=a.pa.N;var c=cc(a);a.Ha=Math.max(a.Ha,c);b.x=c;b.m=a.Ha;b.y=Ma("Height");b.o=Ma("Width");b.w=La();b.b=a.Bb?a.Bb:"";if(a.Vb)b.f=a.Vb;b[""]=vb(a.k);b.t=a.ya;b.V=83;b.tz=(new Date).getTimezoneOffset();b.sn=a.Cb;return b}
k.gc=function(){this.sa.push(1);var a=0;p(this.sa,function(b){a+=b});a<3?(this.xa=h,ac(this)):(this.terminate(),this.F.create("_SUPERFLY_lockout","1",600))};k.wa=function(){};k.zb=function(){var a=cc(this);this.Ha=Math.max(this.Ha,a)};function cc(a){return Math.floor(Ja("Y","Top",!!a.k.scrollElement))}function ac(a){var b=a.ha,b=b?Math.min(b*2,16):1;a.ha=b}k.ra=function(){this.wa();this.terminate()};k.bb=function(){this.q();this.oa()};
function dc(a){if(a.k.virtualReferrer)return h;a=(document.referrer||"").indexOf("://"+l.location.hostname+"/");return a!=-1&&a<9}function ec(a){a=a.k.virtualReferrer;if(!a&&(a=document.referrer||"")){var b=ob(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=R(b.pathname),a=pb(b)}return encodeURIComponent(a)}function fc(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function $b(a){a=[ec(a),Ma("Width"),Ma("Height")];return oa(a)}
function gc(a){var b=[],c=a.F.D("_chartbeat4");c&&(p(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.F.remove("_chartbeat4"));return b}k.terminate=function(){this.O.terminate();this.pa.terminate();F.T(this.ib);this.Va!==g&&pa("load",this.Va);Ca(this.Yb);T().d=g;T().n=g};k.ba=function(){this.terminate();pa("unload",this.Ab);this.Ab=this.Va=this.F=this.sa=this.k=i;this.O.ba();this.O=i;this.pa.ba();this.pa=i;U.U.ba.call(this)};function V(){this.Db=[];this.lc="_p_";this.Za=this.Zb=j;v(l,"beforeunload",s(this.Xc,this));U.call(this)}o(V,U);
V.prototype.q=function(){V.U.q.call(this);var a=l.location;I(this.k,"pingServer","ping.chartbeat.net");I(this.k,"title",document.title);I(this.k,"domain",a.hostname);this.k.domain=u(this.k.domain);I(this.k,"domainAd",this.k.domain);I(this.k,"path",Ub(!!this.k.useCanonical));I(this.k,"engaged",j);this.ea=this.k[rb]||"data-cb-ad-id";this.ta=this.$b=0;this.Gc=function(){var a=r()-this.$b;if(a<500){this.ta&&D(this.ta);var c=s(this.ca,this);this.ta=Da(c,500-a)}else this.xa||this.ca()};this.Fc=F.M("p",
this.Gc,this);this.jd=F.M("z",this.ed,this);if(this.k.krux&&!this.Zb)ka("http://beacon.krzd.net/usermatch.gif?partner=chartbeat&partner_uid="+this.na),this.Zb=h;this.Db=[]};V.prototype.Xc=function(){hc(this);this.ca(h)};V.prototype.wa=function(){this.F.update("_chartbeat4",["t="+this.ya,"E="+this.O.N,"ad="+ra(ic(this,h)),"x="+cc(this),"c="+Math.round((r()-this.ka)/600)/100,"y="+Ma("Height"),"w="+La()].join("&"),60,g,g,1)};function jc(a){return encodeURIComponent("ads."+a.k.domainAd)}
function ic(a,b){var c=[];a.Aa&&p(a.Aa.X,function(a){a=Nb(a);(!b||!(a.aw<=1&&a.ah<=1))&&c.push(Kb(a))});return c.concat(a.Db).join("&")}var kc="h,p,u,d,g,g0,g1,g2,g3,g4,n,nc,f,c,x,m,y,o,w,j,E,v,r,vp,b,t,V,i,tz,l,,ad,z,zz,sn".split(",");k=V.prototype;
k.ca=function(a){this.Cb++;var b=bc(this),c=l.location;b.h=jc(this);b.p=encodeURIComponent(this.k.path);b.u=this.na;b.d=ra(u(c.hostname));dc(this)?b.v=ec(this):b.r=ec(this);b.ad=ra(ic(this));this.$b=r();this.ta&&D(this.ta);Ub(!!this.k.useCanonical);if(this.xa)this.xa=j,b.i=fc(this);this.k.virtualReferrer&&(b.vp=1);var c=this.k.pingServer,d=0;a?b.zz=1:(b.z=gc(this),d=Math.round((this.ha+2)*15E3/1E3));b.j=d;b.l=Tb(this.F)?1:"";this.O.ga=0;this.Ka("https://"+c+"/ping/ad?"+nb(b,kc))};
k.zb=function(){V.U.zb.call(this);lc(this.Aa)};k.Xa=function(a,b){a.H.Pb=b;var c=Nb(a);this.Db.push(Kb(c));a.refresh()};k.ed=function(a,b){for(var c=xa(this.F.D("_chartbeat7")),d=parseInt(c[a.vzcid],10)||0,e={1:h,5:h,15:h,30:h,60:h,100:h};b--;)if(d++,e[d+""]){var f=a,n=d+"second"+(d!==1?"s":""),m=ma(la());ka("http://ohlone.vizu.com/a.gif?vzcid="+f.vzcid+"&vzadid="+n+"&vzsid="+f.vzsid+"&ord="+m)}c[a.vzcid]=d;this.F.create("_chartbeat7",wa(c),7862400)};
function hc(a){a.Aa&&p(a.Aa.X,function(a){if(a.H.Sb)a=a.H,ka("//secure.insightexpressai.com/adServer/cb.gif?bannerid="+a.G.dynamicLogic+"&siteID="+a.G.siteId+"&placementID="+a.G.placementId+"&creativeID="+a.G.creativeId+"&inViewTime="+a.Na.da.N+"&vendor=cb")})}k.terminate=function(){F.T(this.Fc);F.T(this.jd);this.Qa&&F.T(this.Qa);D(this.ta);V.U.terminate.call(this)};function mc(){this.X=[];this.k=l._sf_async_config||{};this.ea=this.k[rb]||"data-cb-ad-id";"postMessage"in window&&v(window,"message",s(this.Qc,this));if(qb()>0){var a=s(this.Ma,this);T().a=a;var a="ad_debug",b="//static.chartbeat.com";Sa()&&(b="//static2.chartbeat.com");b=[b,"js"];Sa()&&(a+="dev");b.push("chartbeat_"+a+".js");Ra(b.join("/"))}this.Ya=[];jb(s(this.q,this))}k=mc.prototype;
k.q=function(a){this.k=l._sf_async_config||{};a?this.B.q():(this.B=new V,this.B.Aa=this);this.Ba={};this.Ga=0;if((a=this.k.engagedAdFilters)&&a.length){var b=this;p(a,function(a){b.Oa(a)})}this.ma();this.Qa=F.M("e",this.Bc,this);try{l.googletag.pubads().addEventListener("slotRenderEnded",s(this.Mc,this))}catch(c){}};k.Mc=function(a){if(this.Ya.length)try{p(this.Ya,s(function(b,d){var e=b.pb;a.slot===e&&(e.setTargeting("_cbr",nc),b.ob>=100||(b.ob+=1),this.Ya.splice(d,1))},this))}catch(b){}};
function oc(){var a=Ha("id^=google_ads_iframe","div");return ua(a,function(a){return a.parentNode})}function pc(a){var b=j;p(a.X,function(a){if(a.Ta)return b=h,j});return b}k.Ma=function(a,b){var c=Ea(F,Wa),d=Ea(J,Eb),e=s(function(){return{engagedAdFilters:this.Ba,maxEngagedAdSpecificity:this.Ga}},this);a.injectDependencies(c,d,e);b.injectDependencies(c);this.Rb=new a;Mb=b;p(this.X,function(a){a.Ma()})};
function lc(a){var b=Ha(a.ea,"div");b.length||(b=oc());b=Ha(a.B.ea,"div");p(b,function(b){if(!qc(a,b)){var d=new K(b);d.H=new Gb;d.H.Na=d;a.X.push(d);d.ma();if(b=E("data-cb-engaged-seconds",b))d=Qb(d),d[O]=parseInt(b,10),a.Oa(d)}})}function qc(a,b){var c;p(a.X,function(a){if(a.qa===b||a.P===b)return c=a,j});return c}
k.ma=function(){var a=S("c"),b=this;lc(b);p(b.X,function(c){c.ma();var d=c.qa;if(a&&a[d]){var e=-1;p(a[d],function(a,d){if(a.e===c.P)return a.c(b.B?b.B.ya:"1",b.B?jc(b.B):"1"),e=d,j});e>-1&&a[d].splice(e,1)}})};k.Qc=function(a){this.bc(B(a.data)?xa(a.data):{},a.source)};
k.bc=function(a,b){if(a.cbType!=="campaignMessage")return j;var c=b;if(c.parent!=window){for(var d=0;c.parent!=window&&d<10;)c=c.parent,d++;if(d>=10)return j}lc(this);var d=document.getElementsByTagName("iframe"),e=g;p(d,function(a){if(a.contentWindow===c)return e=a,j});if(!e)return j;var f,n,d=this.B?this.B.ea:"id^=google_ads_iframe";f=e.getAttribute(d);n=e;if(f===i){n=Ia(e,d);if(!n)return j;f=n.getAttribute(d)}var m=g;p(this.X,function(a){if(f===a.qa&&n===a.P)return m=a,j});if(m===g)return j;m.$a(a,
e);if(d=a[O]){var q=Qb(m);q[O]=parseInt(d,10);this.Oa(q)}d=["cbdata::ack",this.B?this.B.ya:"1",this.B?jc(this.B):"1"].join("::");"postMessage"in b&&b.postMessage(d,"*");return d};
k.Oa=function(a){if(a&&y(a[O])&&!isNaN(a[O])){var b={};p(Pb,function(c){if(B(a[c])||c===O)b[c]=a[c]});var c=Fa(b).length;this.Ga=Math.max(this.Ga,c);this.Ba[c]=this.Ba[c]||[];var c=this.Ba[c],d=j;p(c,function(a){var c=h;p(a,function(a,d){if(d!==O)return c=b[d]===a});(d=c)&&(a[O]=b[O]);return!d});d||c.unshift(b);this.Rb&&this.Rb.update()}};k.oa=function(){this.B.oa()};
k.Yc=function(a,b){if(!a)return j;var c=l.document.getElementById(b);if(!c)return j;var d;c.getAttribute(this.B.ea)&&(d=qc(this,c));var e=this;if(!d){var f=Ha(this.B.ea,"div",c);p(f,function(a){if(d=qc(e,a))return j})}d||(c=Ia(c,this.B.ea))&&(d=qc(this,c));if(!d)return j;d.pb=a;return h};
k.Bc=function(a){if(a&&this.Ga!==0){var b=a.pb,c=this.k.engagedAdCallback;b&&!c&&(c=Aa);if(c)for(var d=this,e=Qb(a),f=e[O],n=this.Ga,m=j;n>0&&!m;)p(this.Ba[n]||[],function(n){m=h;p(n,function(a,b){if(b!==O)return m=a===e[b]});if(m){n=n[O];if(n===-1)return j;if(n===f)e.element=a.P,c(e,f),b&&a.xb==j&&(a.vb?rc(d,a):sc(d,a));return j}}),n--}};k.Xa=function(a){if(a&&(a=qc(this,a)))this.B.Xa(a,1),a.H.kb=1};var nc="0";
function sc(a,b){a.B.Xa(b,2);var c=b.pb;try{c.setTargeting("_cbr",b.ob),a.Ya.push(b),l.googletag.pubads().refresh([c]),b.H.kb=2}catch(d){}}function rc(a,b){(b.Ta||!pc(a))&&p(a.X,function(b){b.vb&&sc(a,b)})}mc.prototype.ra=function(){this.B.wa();this.terminate()};mc.prototype.bb=function(){this.q(h);this.B.oa()};mc.prototype.terminate=function(){this.ib&&F.T(this.ib);this.B&&this.B.terminate();this.Qa&&F.T(this.Qa);p(this.X,function(a){a.terminate()});this.X=[];this.k=i};if(!l.pSUPERFLY_pub){var X=new mc,tc={addEngagedAdFilter:s(X.Oa,X),refreshAd:s(X.Xa,X),updateCampaignData:s(X.ma,X),registerGptSlot:s(X.Yc,X)};tc.evps=s(X.ra,X);tc.svps=s(X.bb,X);"postMessage"in window!==h&&(tc.loadCampaign=s(X.bc,X));l.pSUPERFLY_pub=tc;X.oa()};function uc(a){for(var b=S("m")||[];b.length;)a(b.shift());a={push:a};T().m=a};function vc(){var a=l.location.href,a=a.replace(/-{2,}/g,"-"),a=ob(a);a.pathname=R(a.pathname);return a}
function wc(a){var b=P.D("_chartbeat6");if(!b)return i;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var e,f=vc(),n=pb(f);p(b,function(a,b){var f=a.split(","),m=ya(n,decodeURIComponent(f[0]));if(m===0)return c=f,d=b,j;if(e===g||m<e)e=m,c=f,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+xc(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),f=decodeURIComponent(c[1]),m=c[2];c.splice(0,3);for(var q=c.length/2,w=0;w<q;w++)a.push({qd:b,origin:f,va:m,Cc:c[w*2],fd:c[w*2+1]});
return a}function xc(a){var b="",c;if(!C(a))return b;a.ec&&(c=new Date,c.setTime(c.getTime()+a.ec),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function yc(a){var b=a.topStorageDomain,a=a.domain,c=l.location.hostname;return b?b:zc(c,a)?a:c.replace(/^www\./,"")}function zc(a,b){if(a===b)return h;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return j;if(c.pop()!==d.pop())return j}return h}
function Ac(a,b,c,d){this.Ec=a;this.Dc=b;this.gd=c;this.va=d};function Bc(a,b){for(var c=b||document.documentElement,d=[],e=i,f=a,n,m,q,w,z,L;f&&f!==c;){n=f.nodeName.toLowerCase();e=f;m=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){q=f.children;w=0;for(z=0,L=q.length;z<L;z++){if(e===q[z]){n+="["+(1+z-w)+"]";break}q[z].nodeName!==m&&w++}}d.unshift(n)}return d.join("/")};function Cc(){this.lc="_t_";U.call(this)}o(Cc,U);k=Cc.prototype;
k.q=function(){Cc.U.q.call(this);tb(this.k);var a=l.location;I(this.k,"mabServer","mabping.chartbeat.net");I(this.k,"title",document.title);I(this.k,"domain",a.hostname);I(this.k,"path",Ub(!!this.k.useCanonical));this.Fa=u(a.hostname);this.k.domain=u(this.k.domain);this.cd=yc(this.k);this.Ca=this.Sa=j;this.Ub=[];var b=this,a=wc({domain:"."+this.cd,ec:6E4,path:"/"});if(a!==i)this.Sa=h,p(a,function(a){b.Ub.push(new Ac(a.origin,a.Cc,a.fd,a.va))});this.fc=0;this.cb=i;uc(s(this.Rc,this))};
k.ca=function(){var a=this.O.N,b=Dc(this),c,d=this;this.Sa&&p(this.Ub,function(e){c=b+"&x="+e.Dc+"&v="+e.gd+"&ml="+e.va+"&xo="+e.Ec+"&e="+a;d.Ka(c)});!this.Ca&&this.cb&&Ec(this,this.cb);this.Ca=h};k.ab=function(){var a=l._sf_startpt,b=l._sf_endpt;if(y(a))this.Bb=y(b)?b-a:r()-a;G.q();if(this.Sa)a=s(this.Ia,this),this.Yb=Ba(a,500);this.Ia()};k.Ia=function(){var a,b;this.Ca?(a=this.O.N,b=this.fc*15,a-b>=15&&(this.ca(),this.fc+=1),a>=45&&this.terminate()):this.ca()};
function Dc(a){var b=a.k;return sa()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.Fa)+"&u="+a.na+"&c="+Math.round((r()-a.ka)/600)/100}k.wa=function(){};k.bd=function(a){var b=a.d,c=i;b!==i&&(c={jc:b.s,va:b.g,dc:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.Ca?Ec(this,a):this.cb=a};
function Ec(a,b){var c=Dc(a),d=b.status,e=b.data;if(d=="s"&&e!==i){var f=s(a.Ka,a);C(e.jc)&&p(e.jc,function(a,b){f(c+"&x="+b+"&v="+a+"&ml="+e.va+"&e=-1")});Object.prototype.toString.call(e.dc)==="[object Array]"&&p(e.dc,function(a){f(c+"&me=3&ml="+e.va+"&x="+a)})}else d=="e"&&a.Ka(c+"&me="+b.code)}k.Rc=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],e=a.shift();e==="t"?this.bd.apply(this,a):e==="v"&&this.$c.apply(this,a)}};k.ra=function(){T().m=[];t(this.Jb)&&this.Jb();Cc.U.ra.call(this)};
k.$c=function(a){this.Jb=a};k.terminate=function(){this.Jb=this.rd=g;this.cb=i;this.Ca=this.Sa=g;Cc.U.terminate.call(this)};if(!l.pSUPERFLY_mab){var Fc=new Cc,Hc={};Hc.evps=s(Fc.ra,Fc);Hc.svps=s(Fc.bb,Fc);l.pSUPERFLY_mab=Hc;Fc.oa()};var Ic,Jc,Kc;function Lc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0&&(a=a.substr(16),Mc(),a!=="NONE"))){var a=a.indexOf("HUD2.")===0?a.substr(5):"OLD",b="https://static.chartbeat.com/js/inpage.js";a!=="OLD"&&(b="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+a+".js");Ra(b)}}function Mc(){D(Jc);Jc=g;pa("message",Lc);Kc&&Kc.parentNode&&Kc.parentNode.removeChild(Kc);Kc=g};function Nc(){var a=l._sf_async_config&&l._sf_async_config.domain;if(a&&!Ic){Ic=h;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);v(l,"message",Lc);Jc=Da(Mc,1E4);var b=t(g)?g:{};b.src=a;a=Qa("iframe",b);a.style.display="none";t(g)?g.appendChild(a):document.body&&document.body.appendChild(a);Kc=a}}
function Oc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=Q.J(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Nc(),pa("message",Oc))}};function Y(){"postMessage"in window&&v(l,"message",s(this.Pc,this));U.call(this);sb("_cbq",s(this.hc,this))}o(Y,U);
Y.prototype.q=function(){Y.U.q.call(this);var a=this.na;T().u=a;a=this.ya;T().t=a;this.jb=i;tb(this.k);a=l.location;I(this.k,"pingServer","ping.chartbeat.net");I(this.k,"title",document.title);I(this.k,"domain",a.hostname);this.k.path=this.k.path?R(this.k.path):Ub(!!this.k.useCanonical);this.Fa=u(a.hostname);this.k.domain=u(this.k.domain);this.vc=F.M("c",this.Vc,this);this.wc=F.M("r",this.Wc,this);this.ua=i};Y.prototype.tc=function(a){this.jb=a};
Y.prototype.wa=function(){this.F.update("_chartbeat4",["t="+this.ya,"E="+this.O.N,"EE="+this.pa.N,"x="+cc(this),"c="+Math.round((r()-this.ka)/600)/100,"y="+Ma("Height"),"w="+La()].join("&"),60,g,g,1)};var Pc="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_s,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR,EE".split(",");k=Y.prototype;
k.ca=function(a){this.Cb++;var b=bc(this),c=this.O.ga;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.na;b.d=encodeURIComponent(this.Fa);b.j=Math.round((this.ha+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var d=b.c*6E4+this.ka;b.eD=G.Da("mousedown",d);b.eM=G.Da("mousemove",d);b.eK=G.Da("keydown",d);b.eR=G.Da("resize",d);b.eS=G.Da("scroll",d);G.Zc();G.uc()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=dc(this);if(this.xa){this.xa=j;if(c)this.ua=Qc(this);
b.i=fc(this);d=this.k.hudTrackable;d!==g&&(b.L=d?"1":"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.ua){if(b.v=encodeURIComponent(this.ua.path),b.K=Rc(this.ua),this.ua.yb>1)b.l1=this.ua.yb}else b.v=ec(this);this.k.virtualReferrer&&(b.vp=1)}else b.r=ec(this);c=Ga(b.v);T().v=c;c=Ga(b.r);T().r=c;b.A=this.jb?this.jb:"";b._c=lb("utm_campaign",this.k.campaignTag);b._m=lb("utm_medium",this.k.mediumTag);this.k.idSync?(c=[],ca(new ba,this.k.idSync,c),c=encodeURIComponent(c.join(""))):
c="";b._s=c;b.z=gc(this);b.C=this.k.mobileApp?1:"";b.KK=a?Rc(a):"";b.l=Tb(this.F)?1:"";this.O.ga=0;this.Ka(sa()+"//"+this.k.pingServer+"/ping?"+nb(b,Pc))};
k.Pc=function(a){var b=this.k;if(a.origin==="http://"+(b.playerdomain||this.Fa)){var c=a.data;if(B(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.hc(a));else if(c=="cbdata?"){var c="&u="+S("u"),d="&t="+S("t"),e="&v="+S("v"),f="&r="+S("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+fc(this)+"&referrer="+ec(this)+"&internal="+(dc(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.Fa)+
c+d+e+f+"&utoken="+this.na;a.source.postMessage(b,"*")}}};k.hc=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.ha=0};function Sc(a){a=a.replace(/-{2,}/g,"-");a=ob(a);a.pathname=R(a.pathname);return a}k.Vc=function(a){Tc(this,a,"c")};k.Wc=function(a){Tc(this,a,"r")};
function Tc(a,b,c){if(a.Za&&r()-a.ka>=a.wb)a.terminate();else{var d=b.href||"",d=Sc(d);if(d.protocol.indexOf("http")===0){var e=d.hostname!==l.location.hostname,d=pb(d),f=Na(b,function(a){return a.id}),n=Bc(b,f),m;f?(n&&(n="/"+n),n="*[@id='"+f.id+"']"+n,m=Bc(b)):m=n;f=ma(n);m=ma(m);b=Bb(b,g,h);c={left:b.x,top:b.y,path:a.k.path,href:d,Mb:f,hb:m,Lb:n,Eb:c,yb:0,Ic:a.k.domain};a.ca(c);e||a.F.update("_chartbeat5",Uc(c),60,j,g,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function Rc(a){return[a.left,a.top,a.Mb,encodeURIComponent(a.Lb),a.Eb,encodeURIComponent(a.href),a.hb].join("::")}function Uc(a){var b=encodeURIComponent(a.Lb),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.Mb,b,a.Eb,a.hb,encodeURIComponent(a.Ic)].join(",")}
function Qc(a){var b=a.F.D("_chartbeat5");if(!b)return i;var c=a.k.domain,d=b.split("::"),b=d.length,e,f=i,n,m=Sc(l.location.href),q=pb(m);p(d,function(a,b){var d=a.split(","),m=d.length>8?decodeURIComponent(d[8]):j;if(m&&m!==c)return h;m=ya(q,decodeURIComponent(d[3]));if(m===0)return e=d,f=b,j;if(n===g||m<n)n=m,e=d,f=b});if(f===i)return i;d.splice(f,1);a.F.create("_chartbeat5",d.join("::"),60);(a=e[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:e[0],top:e[1],path:decodeURIComponent(e[2]),
href:decodeURIComponent(e[3]),Mb:e[4]||"",Lb:a,hb:e.length>7?e[7]:"",Eb:e.length>6?e[6]:"c",yb:b}}k.terminate=function(){F.T(this.vc);F.T(this.wc);Y.U.terminate.call(this)};if(!l.pSUPERFLY){var Vc=new Y,Wc={};l.pSUPERFLY=Wc;var Xc=l.pSUPERFLY_mab,$=l.pSUPERFLY_pub,Yc=[];Xc&&Yc.push(Xc);if($)Yc.push($),$.addEngagedAdFilter&&(Wc.addEngagedAdFilter=$.addEngagedAdFilter),$.refreshAd&&(Wc.refreshAd=$.refreshAd),$.registerGptSlot&&(Wc.registerGptSlot=$.registerGptSlot),sb("_cba",function(a){a()});Wc.virtualPage=function(a,b){if(!cb){var c=l._sf_async_config;c.virtualReferrer=sa()+"//"+c.domain+c.path;c.path=R(a);b&&(c.title=b);Vc.ra();p(Yc,function(a){a.evps()});Vc.bb();p(Yc,
function(a){a.svps()})}};Wc.activity=s(Vc.tc,Vc);Vc.oa();var Zc=Q.J(h);if(Zc)if(Zc.getItem("_cb_ip")){var $c=l.location;(!/^(.+[.])?chartbeat\.com$/.test($c.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test($c.pathname))||Nc()}else v(l,"message",Oc)};})();
