(function(z){
var CL=function(a,b,c){b="new"===(b||a.nd);return c?(a=a.d.u.v().get(z.U.Gp),b?-1:-a):a.fl+(b?-1:1)};var DL=function(a){z.Ov.call(this,a);this.fl=0;this.nd="new"};var EL=function(a,b){a.UX=b};
var FL=function(a){return(0,z.Q)('\x3cdiv class\x3d"fyre '+(a.Jd?"fyre-liveblog ":"")+(a.dh?"fyre-livechat ":"")+(a.nU?"fyre-bootstrap ":"")+(a.se?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Sa?"fyre-avatar-disabled":"")+'"\x3e'+(0,z.Q)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Sa?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.ro?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var GL=function(a){return(0,z.Q)('\x3ca href\x3d"'+z.R(z.S(a.Aa))+'" title\x3d"'+z.R(a.da)+'" data-id\x3d"'+z.R(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.R(a.WT)+'"\x3e\x3cimg src\x3d"'+z.R(z.S(a.zd))+'" alt\x3d"'+z.R(a.da)+'" onerror\x3d"javascript:this.src\x3d\''+z.R(z.fp(a.cc))+"';\" /\x3e\x3c/a\x3e")};
var HL=function(a){return(0,z.Q)(z.fr(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.P(a.j.qO)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(a.j.dy)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(a.j.Xo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(a.j.ey)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var IL=function(a){return(0,z.Q)('\x3cdiv class\x3d"tooltip"\x3e'+z.P(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var JL=function(){};var KL=function(a){this.IG=!1;this.Mo=[];this.zb=null;z.Ff.call(this,a)};var LL=function(a,b){z.Hj.call(this,b,a)};var ML=function(a,b){z.sG.call(this,a,b)};
var NL=function(a,b){var c=a.d.Jb;c.ph[4]&&(z.Bz(c,4,(0,z.t)(function(a){b.e(a,"threadBreakout",this.Or)},a)),z.Dz(c,4,(0,z.t)(function(a){b.Ja(a,"threadBreakout",this.Or)})))};var OL=function(a,b){var c=[a.qm,a.yz];a.zg&&c.push(a.zg);a.ut&&c.push(a.ut);a.zz&&c.push(a.zz);z.y(c,function(a){z.mk(a,"fyre-stream-sort-selected")});z.kk(b,"fyre-stream-sort-selected")};var PL=function(a,b){z.sG.call(this,a,b)};
var QL=function(a,b){z.dy.call(this,a,b);this.bh=!1;this.RI=!!this.C.L.LG;this.Ha=new z.my;this.Ha.sc(this);this.su="archiveShowMore"};var RL=function(a,b){z.pG.call(this,a,b)};var SL=function(a,b,c){z.lu.call(this,a,b,c);this.Uz=b||"";this.xg(IL(this.s()))};var TL=function(a,b,c){z.fu.call(this,a,b||3,c)};var UL=function(a,b){z.T.call(this,b);this.l=a};var VL=function(a,b){z.T.call(this,b);this.Dc=a};var WL=function(a,b){VL.call(this,a,b)};
var XL=function(){var a=z.u.window,b=z.u.document;function c(){var a=v.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){v.xX||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(v,g)}function f(a){var b;if(a.AP)return a;if(v.wX&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.AP=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.iU&&a.iU("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var v={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.wX,shivMethods:!1!==g.xX,type:"default",shivDocument:f};f(b)};var YL=function(a,b){z.AG.call(this,a,b);a.L.uP||XL();var c=a.u.Cc(),d=a.u.v();this.ni=new z.qG(a,a.Ql.xa,d.dh()||z.dg);this.F(this.ni);a.L.Sa||(this.Fn=new WL(c),this.F(this.Fn));this.Wr=new z.oG;this.F(this.Wr)};var ZL=function(a){var b=z.F.mb()||z.F.get(z.E.Ip);return!a.w.Jd()||b};var $L=function(a){z.Kz.call(this,a);this.Wm=1};
var aM=function(a){z.Ys.call(this,a);z.ov(a.u);this.Tb=new YL(a);this.br.start();this.Gl(this.Tb);z.ct(this)};var bM=function(a,b){this.fD=LL;this.TJ=aM;z.W.lm(b.strings||{});z.Mn.call(this,a,b);this.Wa.Lb.send(z.bo("Init"))};var cM=function(a){a.qk&&(a.qk.q(),delete a.qk)};z.w(DL,z.Ov);z.e=DL.prototype;z.e.sl=z.l(61);z.e.LF=z.l(63);z.e.MF=z.l(62);z.e.LF=z.K(63,function(a){this.La||(this.Io[a]=!1,z.Pv(this,a,function(a){a.N(a.ya.Vm)}))});
z.e.MF=z.K(62,function(a,b){if(!this.La){var c=this.d.u.v(),d=z.Yu(a,b),f=c.get(z.U.Pt);c.set(z.U.Gp,d.CV);z.A(d.cb,(0,z.t)(this.d.U.N,this.d.U,"bootstrap_author_received"));d.content=z.jj(d.content,function(a,b){return!z.Sa(f,b)});z.A(d.content,function(a){z.kb(d.content,z.Rv(this,a))},this);z.kb(this.rc,z.ij(d.content,z.Db(a)));this.be(a,d.content);z.Pv(this,a,function(b){b.N(b.ya.Hk,{Od:a});b.set(b.k.of,!0)})}});
z.e.sl=z.K(61,function(a,b){this.fl=a;this.nd=b||this.nd;var c=this.Pd[a]=new z.Kv;z.Ou.D();var d=this.d.u.v(),f=(0,z.t)(this.MF,this,a),g=(0,z.t)(this.LF,this,a),h=this.d.L.an,d=d.get(z.U.wc),h=z.x.Xu(d,h)+String(a)+".json";z.Pu(0,h,f,g);return c});z.WG.prototype.sl=z.K(60,function(a,b){this.Qk||(this.Qk=new DL(this.C));var c=this.Qk,d=CL(c,a,b);return c.sl(d,a)});z.Ou.prototype.Th=z.K(52,function(a,b,c){a=z.wa("%s%scollection/%s/hot/",z.x.H.Ad,z.x.kf,a.sa);(new z.Pe({url:a,ua:b,na:c})).send()});
z.ew.prototype.Th=z.K(51,function(a){var b={sa:this.d.u.v().id},c=z.Ou.D().Th;z.fw(this,c,b,a);return a});z.WG.prototype.Th=z.K(50,function(){z.kw(this);this.Oi=new z.ew(this.C,void 0);var a=new z.Kv;this.Oi.Th(a);return a});z.Ou.prototype.Ph=z.K(49,function(a,b,c){a=z.wa("%s%scollection/%s/top/%s/",z.x.H.Ad,z.x.kf,a.sa,a.jO);(new z.Pe({url:a,ua:b,na:c})).send({format:"stream"})});z.ew.prototype.Ph=z.K(48,function(a,b){var c={sa:this.d.u.v().id,jO:a},d=z.Ou.D().Ph;z.fw(this,d,c,b);return b});
z.WG.prototype.Ph=z.K(47,function(a){z.kw(this);this.Oi=new z.ew(this.C,void 0);var b=new z.Kv;this.Oi.Ph(a,b);return b});z.T.prototype.XG=z.K(46,function(){return this.Z});z.Ej.prototype.ro=z.K(45,function(){return this.get(this.k.Fp)});z.w(JL,z.Sn);z.ca(JL);var dM={ZY:"attachmentDelegate"};z.kb(dM,z.nH);JL.prototype.oo=function(a){var b=JL.b.oo.call(this,a),c=a.attachmentDelegate;c&&(b.sO=c);b.Xx=a[dM.ZL]||null;return b};z.w(KL,z.Ff);KL.prototype.KU=function(a){this.zb||(this.zb=z.u.setInterval((0,z.t)(this.yQ,this),5E3));this.Mo=this.Mo.concat(a)};
KL.prototype.yQ=function(){this.Mo.length&&(this.IG||(z.uc("//platform.twitter.com/impressions.js"),this.IG=!0),z.u.twttr=function(){var a=z.u.twttr||{},b=a.impressions||{};b._e=b._e||[];b.ready=b.ready||function(a){b._e.push(a)};a.impressions=b;return a}(),z.u.twttr.impressions.ready((0,z.t)(function(a){a.impressions.logTweets(this.Mo,{partner:"livefyre"});this.Mo=[]},this)))};KL.prototype.q=function(){(0,window.clearInterval)(this.zb);KL.b.q.call(this)};z.w(LL,z.Hj);LL.prototype.jz=function(a){this.Eu=new z.Wq(this,a);this.Lb=new z.Un(this);this.Lc=new z.xi(this);this.u=new z.lv(this,a);this.hb=new z.xv(this,a);this.Nb=new z.WG(this,a);this.Ql=new z.Gv(this);new z.qf;this.cp=new z.Lw(this,a);this.Gz=new z.lw(this);this.Ji=new z.Aw(this);this.Vz=new z.Qu(this,a);this.pY=new KL(this);this.Jb=new z.rz(this)};z.w(ML,z.sG);z.e=ML.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.Sx=b.v().Jd();a.zV=!z.F.get(z.F.k.Xd);a.Id=b.Id(z.F.id);a.xP=2===c.get(z.U.bj);a.wP=3===c.get(z.U.bj);a.j={DU:z.W.get(z.W.g.gu),GU:z.W.get(z.W.g.hu),UT:z.W.get(z.W.g.mB),dy:z.W.get(z.W.g.aq),ey:z.W.get(z.W.g.bq),Xo:z.W.get(z.W.g.nC),mp:z.W.get(z.W.g.fq),hY:z.W.get(z.W.g.EC)};return a};
z.e.K=function(a){ML.b.K.call(this,a);a=this.c;var b;b=this.s();var c=z.Q,d=z.fr(b),f;f=b.Sx?(0,z.Q)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.zV?b.Id?z.P(b.j.GU):z.P(b.j.DU):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(b.j.dy)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Xo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(b.j.ey)+"\x3c/a\x3e"+(b.xP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Xo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.P(b.j.hY)+"\x3c/a\x3e":"")+(b.wP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Xo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.P(b.j.UT)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.rl=this.o("fyre-follow-conversation");this.ut=this.o("fyre-stream-sort-hot-threads")||
null;this.zz=this.o("fyre-stream-sort-top-comments")||null;this.zg=this.o("fyre-stream-sort-back");this.qm=this.o("fyre-stream-sort-newest");this.yz=this.o("fyre-stream-sort-oldest");this.WI=this.o("fyre-stream-sort-options");this.cd=this.o("fyre-content-loading");this.Gd()};z.e.m=function(){ML.b.m.call(this);var a=this.p();z.F.on(z.F.ya.Vf,this.ho,this);a.e(this.c,"click",this.lb);z.y([3,4,5],function(b){z.tG(this,a,b)},this);NL(this,a)};
z.e.lb=function(a){a.preventDefault();a=a.target;if(!z.qk(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.zg)if(a===this.rl)this.JF();else{OL(this,a);this.pm();var b=null;switch(a){case this.ut:this.tE();b="hottest";break;case this.zz:this.dispatchEvent({type:"sortTopComments",Xb:(0,z.t)(this.Gd,this)});b="top_comments";break;case this.qm:this.un("new");b="newest";break;case this.yz:this.un("old"),b="oldest"}this.d.Lb.send(z.bo("SortStream",{Fs:b}))}};
z.e.Fi=function(a,b){a&&this.kz(b);z.Cl(this.WI,"display",a?"none":"block");z.Cl(this.zg,"display",a?"block":"none")};z.e.kz=function(a){var b=this.qm,c=this.un,d=z.W.get(z.W.g.Qt);4===a&&(b=this.ut,c=this.tE,d=z.W.get(z.W.g.hK));this.zg.innerHTML=d;this.p().Kd(this.zg,"click",(0,z.t)(function(a){a.stopPropagation();this.Fi(!1);OL(this,b);c.apply(this)},this))};z.e.bo=function(a){a.stopPropagation();this.Fi(!1);OL(this,this.qm);this.un()};
z.e.Or=function(a){var b=a.Xb;z.kb(a,{Xb:(0,z.t)(function(){b();this.Fi(!0,4)},this)})};z.e.un=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Xb:(0,z.t)(this.Gd,this)})};z.e.tE=function(){this.dispatchEvent({type:"sortHotThreads",Xb:(0,z.t)(this.Gd,this)})};z.e.JF=function(){var a=this.d.u;a.v();var b=z.F.k;z.F.id?(b=a.Id(z.F.get(b.X)),a.Aj(!b),a=b?z.W.get(z.W.g.gu):z.W.get(z.W.g.hu),this.rl.innerHTML=a):z.Sh(this.d.Lc,(0,z.t)(this.JF,this))};
z.e.ho=function(){var a=this.d.u,b=a.v(),c=z.F.k,b=!b.Jd()||z.F.get(c.Xd);this.rl&&(b?z.N(this.rl,!1):(a=a.Id(z.F.id)?z.W.get(z.W.g.hu):z.W.get(z.W.g.gu),this.rl.innerHTML=a,z.N(this.rl,!0)))};z.e.h=function(){ML.b.h.call(this);z.F.off(null,null,this)};z.w(PL,ML);PL.prototype.K=function(a){this.c=a;z.yo(a,HL,this.s());this.qm=this.o("fyre-stream-sort-newest");this.yz=this.o("fyre-stream-sort-oldest");this.WI=this.o("fyre-stream-sort-options");this.cd=this.o("fyre-content-loading");this.Gd()};PL.prototype.un=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.UX.stream,direction:a,Xb:(0,z.t)(this.Gd,this)})};
PL.prototype.s=function(){return{j:{qO:z.W.get(z.W.g.cK),dy:z.W.get(z.W.g.aq),ey:z.W.get(z.W.g.bq),Xo:z.W.get(z.W.g.nC),mp:z.W.get(z.W.g.fq)}}};z.w(QL,z.dy);z.e=QL.prototype;z.e.jn=function(a){this.clear();z.N(this.c,!0);this.nd=a};z.e.clear=function(){this.ld.Lf();this.Ab={};this.Hj=[];for(this.qh=this.Vk=null;this.ma&&0!=this.ma.length;)this.Po(0).q()};z.e.K=function(a){QL.b.K.call(this,a);z.yo(this.c,z.gr,this.s());this.ik=this.o("fyre-stream-content");this.Gi=this.o("fyre-stream-more");this.Ha.S(this.Gi);z.N(this.Gi,!1)};z.e.h=function(){this.Ha&&this.Ha.q();this.Ha=null;QL.b.h.call(this)};
z.e.m=function(){QL.b.m.call(this);this.p().e(this.Ha,"showMore",this.ax)};z.e.ew=function(){return this.C.L.LG};z.e.s=function(){return{ce:z.x.H.ob,uv:!!this.Ha,j:{qz:z.W.get(z.W.g.dK)}}};z.e.bx=function(){this.Ha.pt();this.bh=!0};z.e.vy=function(){this.dispatchEvent({type:this.su,direction:this.nd,target:this,xY:this.bh&&this.RI,Xb:(0,z.t)(this.bx,this),zj:(0,z.t)(this.iG,this)});this.bh&&(this.RI=!1)};z.e.Cy=function(a){this.bh||QL.b.Cy.call(this,a)};
z.e.bp=function(){var a=this.C.Nb.Qk,b=this.nd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.Gp),c=!b&&a.fl>-c;b&&-1>a.fl||c?this.Ha.show():this.Ha.rb()};z.e.start=function(){this.bh||this.vy()};z.w(RL,z.pG);var eM=z.W.g,fM={};fM.comment=[eM.Qm,eM.Wf,eM.Fm];fM.liveblog=[eM.BM,eM.NL,eM.sB];RL.prototype.fF=function(a){function b(a){return z.Ga(a,"%s")?a:"%s "+a}var c=this.l.Jd()?"liveblog":"comment",c=fM[c];switch(a){case 1:c=b(z.W.get(c[1]));break;case 0:if(z.W.get(c[0])!==z.nG[c[0]]){c=z.W.get(c[0]);break}default:c=b(z.W.get(c[2]))}return z.wa(c,a)};z.w(SL,z.lu);SL.prototype.ep=200;SL.prototype.Vh=function(){return new TL(this.Kc)};SL.prototype.s=function(){var a={};a.message=this.Uz;return a};z.w(TL,z.fu);TL.prototype.Pc=function(a,b,c){var d=z.am(this.element),d=new z.Ch(d.width,d.height+25);b=z.au(this.element,this.Jh,a,b,d,c,9);z.Il(a.lastChild,0);b&&(d=new z.Ch(0,-5),z.au(this.element,2,a,1,d,c,5),z.Il(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.w(UL,z.T);z.e=UL.prototype;z.e.r=function(){this.c=z.Bo(GL,this.s())};z.e.m=function(){UL.b.m.call(this);this.Va=new SL(this.c,this.l.get("displayName"));this.p().e(this.c,"click",this.lb)};z.e.h=function(){UL.b.h.call(this);this.Va&&this.Va.q()};z.e.s=function(){var a=z.Vd,b={};b.zd=this.l.get(a.xb);b.cc=this.l.get(a.wk);b.da=this.l.get(a.va);b.id=this.l.id;b.WT=this.l.id.replace(/[@.]/g,"-");b.Aa=this.l.get(a.Zb);return b};
z.e.lb=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.l,type:"author_click"})};z.w(VL,z.T);z.e=VL.prototype;z.e.wB=10;z.e.h=function(){VL.b.h.call(this);delete this.Dc};z.e.Q=function(){VL.b.Q.call(this);this.Dc.off(null,null,this)};z.e.tF=function(a){a=new UL(a);var b=this.Nc();if(b===this.wB){var c=this.Po(b-1);c&&(c.q(),b--)}0<b?this.Ge(a,0,!0):this.F(a,!0)};z.e.ZS=function(a){var b;this.Xc(function(c){a.id===c.l.id&&(b=c)});b&&(this.removeChild(b),b.q())};
z.e.co=function(){this.Dc.on(this.Dc.ya.Ot,this.tF,this);this.Dc.on(this.Dc.ya.ou,this.ZS,this);var a=this.Dc.sb.reverse().slice(0,this.wB);z.y(a,this.tF,this)};z.w(WL,VL);z.w(YL,z.AG);
YL.prototype.mI=function(a,b){if(!this.La){this.w=b;var c=b.get(z.U.zh),d=b.get(z.U.Zd);this.It=new z.xG(c,d,a.L.Sa);this.F(this.It);this.Lq=new RL(a.u.v());this.F(this.Lq);this.Bs=null;b.ro()&&(this.Pu=new PL(a),this.F(this.Pu),this.Rk=new QL(a),this.F(this.Rk),EL(this.Pu,{stream:this.Rk}));this.nh=new ML(a);this.F(this.nh);this.ts((0,z.t)(function(a){this.dc=a;this.F(this.dc);a=this.dc;this.Z&&a&&a.S(this.ke,!0)},this));b.get(z.U.Lm)&&!z.dg&&this.w.ir()&&(this.w.dh()||this.w.Jd()||this.Hw())}};
YL.prototype.s=function(){return{Sa:this.d.L.Sa,dh:this.w.dh(),Jd:this.w.Jd(),se:z.dg,nU:this.d.L.pD,ro:this.w.ro()}};z.sy={VY:"fyre-archive-stream",WY:"fyre-archive-stream-header",N1:"fyre-top-content-stream",g2:"fyre-widget",Lm:"fyre-featured-content-wrapper"};z.kb(z.sy,z.nK);z.e=YL.prototype;
z.e.r=function(){this.c=z.Bo(FL,this.s());var a=this.w.get(z.U.bj);if(1!==a){var b=this.d.Jb,a=2===a?3:4,c=this.o("fyre-top-content-stream");z.sz(b,a,c,this)}this.Wr.S(this.o(z.sy.yL));this.Rk&&(b=this.o("fyre-archive-stream-header"),this.Pu.S(b),this.Rk.S(this.o("fyre-archive-stream")));this.Kh(1);this.ke=this.o(z.sy.wh);b=ZL(this);z.N(this.ke,b)};
z.e.m=function(){YL.b.m.call(this);var a=this.dc;this.Z&&a&&a.S(this.ke,!0);this.d.U.op("stream_data_received",this.XR,this);this.p().e(this,"request_content_context",this.uR).e(this,"request_content_reply",this.bT);this.Rk&&this.Rk.start()};z.e.co=function(){this.Fn&&this.Fn.co()};z.e.XR=function(){var a=this.w,b=a.get(z.U.Ak);z.th||b||(b=(0,z.t)(function(){this.Bs=new z.gM(this.d,a.get(z.U.Zd));this.F(this.Bs,!0)},this),z.uc(z.x.H.ob+z.x.Gf.Bs,null,null,b))};
z.e.Hw=function(){var a=new z.gF(this.XG,this);a.NH=(0,z.t)(this.SW,this);var b=(0,z.t)(function(){a.start(0,2E3)},this);z.uc(z.x.H.ob+z.x.Gf.cQ,null,null,b)};z.e.SW=function(){var a=this.o("fyre-featured-content-wrapper");this.Ov=new z.DK(this.d);this.F(this.Ov);this.Ov.S(a);this.Ov.ah()};z.e.ts=function(a){if(!this.d.L.readOnly){var b=this.d.u.v();z.gx(z.dx.D(),"main",a,{C:this.d,xi:"new"},b);z.F.on(z.F.mc(z.F.k.X),this.Yc,this)}};z.e.Yc=function(){if(this.ke){var a=ZL(this);z.N(this.ke,a)}};
z.e.$h=function(){0<z.Hp(this,this.dc)&&(this.removeChild(this.dc),this.dc.q());this.ts((0,z.t)(function(a){this.dc=a;this.F(this.dc);a=this.dc;this.Z&&a&&a.S(this.ke,!0);z.N(this.ke,!0)},this))};z.e.$g=function(a,b){null!=a&&(this.d.Jb.wl(1),(0,window.setTimeout)((0,z.t)(function(){var c=b&&function(a){z.cx(a.Xa)};this.La||z.BG(this,a,c)},this),3E3))};z.e.uR=function(a){z.BG(this,a.Zk)};z.e.bT=function(a){z.BG(this,a.Zk,function(a){z.cx(a.Xa)})};
z.e.h=function(){YL.b.h.call(this);z.F.off(z.F.mc(z.F.k.X),this.Yc,this);this.w&&(this.w.off(null,null,this),this.w=null)};z.w($L,z.Kz);z.e=$L.prototype;z.e.pe=function(a,b){$L.b.pe.call(this,a,b);a.e(b,"repliesExpanded",this.GF);a.e(b,"sortHotThreads",this.nT);a.e(b,"sortOrderChanged",this.lG);a.e(b,"sortTopComments",this.oT);a.e(b,"archiveShowMore",this.dR);a.e(b,"archiveSortOrderChanged",this.eR)};
z.e.dR=function(a){var b=a.Xb||z.n,c=(0,z.t)(this.Se,this,a.target),d=this.d.Nb;a=a.xY;d.Qk||(d.Qk=new DL(d.C));d=d.Qk;a=a?d.fl:CL(d);var f=d.dd[a];f&&(d.fl=a);if(f)b(),c(f);else{d=this.d.Nb.sl();a=d.k.of;if(d.get(a))b();else d.on(d.mc(a),b,this);z.Lz(this,d,c)}};z.e.Cw=function(a,b){var c=2===b.ed,d=1!==b.ed;switch(b.type){case 0:var f=this.d.u.v(),f=z.Mm(b,f),g=f.get(z.an),g=this.d.u.cb().get(g);f.set(z.Nm,g);a.Tw(f,c,d)}};
z.e.dG=function(a){if(1!==this.Wm){var b=this.MX.nh;b.Fi(!1);OL(b,b.qm);z.kb(a,{direction:"new",Xb:z.n});this.lG(a)}};z.e.eR=function(a){z.Mz(this);a.stream.jn(a.direction);var b=this.d.Nb.sl(a.direction,!0),c=(0,z.t)(function(b){a.Xb();this.Se(a.stream,b)},this);z.Lz(this,b,c,a.zj)};z.e.lG=function(a){this.d.L.fi=null;var b=z.Oz(this,1);z.kw(this.d.Nb);b.jn(a.direction);var c=z.jw(this.d.Nb,a.direction),d=(0,z.t)(function(c){a.Xb();this.Se(b,c)},this);z.Lz(this,c,d,a.zj)};
z.e.oT=function(a){var b=z.Oz(this,3),c=this.d.Nb.Ph("likes");z.Lz(this,c,(0,z.t)(function(c){a.Xb();z.hb(c)?z.cy(b):this.Se(b,c)},this))};z.e.nT=function(a){var b=z.Oz(this,4),c=this.d.Nb.Th();z.Lz(this,c,(0,z.t)(function(c){a.Xb();z.hb(c)?z.cy(b):this.Se(b,c)},this))};z.w(aM,z.Ys);z.e=aM.prototype;z.e.c=null;z.e.h=function(){aM.b.h.call(this);this.wt.q();this.JD.q();this.Tb.Z&&this.Tb.q();this.Tf&&this.Tf.q();delete this.Tf};z.e.Gl=function(a){aM.b.Gl.call(this,a);this.wt=new $L(this.d);this.wt.handle(a);this.JD=new z.Hz(this.d);this.JD.handle(a)};z.e.Hz=function(){this.d.Ji.stop()};z.e.TX=function(){this.d.Ql.stop()};z.e.fk=function(){this.d.Ji.start()};z.e.QX=function(){this.d.Ql.start()};
z.e.pa=function(){this.Tf&&this.Tf.q();this.Tb.pa(this.c);this.d.Lb.send(z.bo("Load"));var a=z.$s(window.location,"reply_editor");if("object"===typeof window.Livefyre&&window.Livefyre.bO)z.dt(this,a);else{var b=z.at(this);this.Tb.$g(b,a)}this.d.U.N("render_complete",this.c)};z.w(bM,z.Mn);bM.prototype.aD=JL.D();bM.prototype.h=function(){bM.b.h.call(this);this.stop();delete this.L;delete this.ha;cM(this);z.Rn(this);this.yj&&(this.yj.q(),delete this.yj)};bM.prototype.Pz=function(){this.stop();cM(this);bM.b.Pz.call(this)};z.lg.main.Lh.ia(bM);})(fyre.conv);
